import type { Campaign, Join, MusicTrack, Note, Post } from "@/lib/qonvo-data";
import { parseMusicUrl } from "@/lib/qonvo-data";

function poster(bg: string, label: string) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="800" height="360"><rect fill="${bg}" width="800" height="360"/><text x="36" y="196" fill="#f3f3f0" font-size="34" font-family="Segoe UI,sans-serif">${label}</text></svg>`;
  return `data:image/svg+xml;charset=utf-8,${encodeURIComponent(svg)}`;
}

export const DEMO_POSTS: Post[] = [
  {
    id: "demo-feed-1",
    title: "Lagos night market still hits different",
    body: "Balogun after 8pm is a whole city. Who is going this weekend?",
    excerpt: "Night market energy in Lagos — who is outside?",
    author: "Amaka#2201",
    ts: Date.now() - 3600_000,
    comments: (() => {
      const ts = Date.now() - 1800_000;
      return [
        { author: "Tunde#104", body: "Lekki side too.", ts },
        { author: "Kemi#0092", body: "Balogun is the one.", ts: ts + 20_000, parentTs: ts },
      ];
    })(),
    category: "Naija",
    tags: "lagos, night",
    link: "https://en.wikipedia.org/wiki/Lagos",
    image: poster("#1f3d2e", "Lagos after dark"),
    slug: "lagos-night-market",
    status: "publish",
  },
  {
    id: "demo-feed-2",
    title: "Best jollof is not even a debate",
    body: "Party jollof with that smoky bottom. I said what I said.",
    excerpt: "Party jollof vs restaurant jollof.",
    author: "Kemi#0092",
    ts: Date.now() - 7200_000,
    comments: [],
    category: "Culture",
    tags: "food",
    image: poster("#3b2a16", "Jollof talk"),
    slug: "jollof-debate",
    status: "publish",
  },
  {
    id: "demo-feed-3",
    title: "Remote jobs that actually pay in Naira + USD",
    body: "Share roles that paid on time. No fairy tales.",
    excerpt: "Real remote pay, not screenshots.",
    author: "Chidi#4410",
    ts: Date.now() - 10800_000,
    comments: [{ author: "Zara#77", body: "Product design internships too.", ts: Date.now() - 9000_000 }],
    category: "Business",
    tags: "work, remote",
    link: "https://www.who.int/",
    image: poster("#1a2744", "Work board"),
    slug: "remote-jobs-naija",
    status: "publish",
  },
  {
    id: "demo-feed-4",
    title: "Super Eagles lineup talk",
    body: "Drop your XI before the next qualifier. No recency bias.",
    excerpt: "Your starting XI.",
    author: "Baba#12",
    ts: Date.now() - 14400_000,
    comments: [],
    category: "Sports",
    tags: "football",
    image: poster("#14351f", "Match day"),
    slug: "eagles-lineup",
    status: "publish",
  },
  {
    id: "demo-feed-5",
    title: "New phones in Computer Village",
    body: "Prices moved again. If you bought this week, drop the figure.",
    excerpt: "Street prices, not flyer prices.",
    author: "Ife#830",
    ts: Date.now() - 18000_000,
    comments: [],
    category: "Tech",
    tags: "phones",
    image: poster("#2a2438", "Gadget run"),
    slug: "computer-village",
    status: "publish",
  },
];

export const DEMO_ADS: Campaign[] = [
  {
    id: "demo-ad-hero",
    name: "Paystack for hustle",
    note: "Collect payments in Naira.",
    ts: Date.now() - 4000_000,
    status: "approved",
    placement: "board",
    amount: "80 USDT",
    coin: "usdt",
    txHash: "0xdemohero001",
    link: "https://paystack.com",
    image: "https://picsum.photos/seed/paystack-ad/640/160",
    kind: "image-text",
    views: 1280,
  },
  {
    id: "demo-ad-side",
    name: "Glo data bundle",
    note: "Stay online.",
    ts: Date.now() - 3000_000,
    status: "approved",
    placement: "board",
    amount: "40 USDC",
    coin: "usdc",
    txHash: "0xdemoside001",
    link: "https://gloworld.com",
    image: "https://picsum.photos/seed/glo-ad/640/160",
    kind: "image",
    views: 940,
  },
  {
    id: "demo-ad-chat",
    name: "Spotify Naija mix",
    note: "Afrobeats this week.",
    ts: Date.now() - 2000_000,
    status: "approved",
    placement: "board",
    amount: "55 USDC",
    coin: "usdc",
    txHash: "0xdemochat001",
    link: "https://open.spotify.com",
    image: "https://picsum.photos/seed/spotify-ad/640/160",
    kind: "image-text",
    views: 2104,
  },
  {
    id: "demo-ad-mtn",
    name: "MTN pulse",
    note: "Data that lasts.",
    ts: Date.now() - 1800_000,
    status: "approved",
    placement: "board",
    coin: "eth",
    link: "https://www.mtn.ng",
    image: "https://picsum.photos/seed/mtn-ad/640/160",
    kind: "image",
    views: 640,
  },
  {
    id: "demo-ad-jumia",
    name: "Jumia deals",
    note: "Shop today.",
    ts: Date.now() - 1600_000,
    status: "approved",
    placement: "board",
    coin: "btc",
    link: "https://www.jumia.com.ng",
    image: "https://picsum.photos/seed/jumia-ad/640/160",
    kind: "image-text",
    views: 402,
  },
  {
    id: "demo-ad-bolt",
    name: "Bolt rides",
    note: "Move around town.",
    ts: Date.now() - 1400_000,
    status: "approved",
    placement: "board",
    coin: "sol",
    link: "https://bolt.eu",
    image: "https://picsum.photos/seed/bolt-ad/640/160",
    kind: "text",
    views: 188,
  },
  {
    id: "demo-ad-yt",
    name: "Nollywood trailer",
    note: "Watch the teaser.",
    ts: Date.now() - 1200_000,
    status: "approved",
    placement: "board",
    coin: "usdc",
    link: "https://www.youtube.com/watch?v=kJQP7kiw5Fk",
    video: "kJQP7kiw5Fk",
    kind: "video-text",
    views: 3301,
  },
  {
    id: "demo-ad-yt2",
    name: "Afrobeats live",
    note: "",
    ts: Date.now() - 1100_000,
    status: "approved",
    placement: "board",
    coin: "sol",
    video: "9bZkp7q19f0",
    kind: "video",
    views: 5120,
  },
  {
    id: "demo-ad-wait",
    name: "Pending crypto review",
    note: "Waiting on hash check.",
    ts: Date.now() - 600_000,
    status: "paid",
    placement: "board",
    amount: "50 USDT",
    coin: "usdt",
    txHash: "0xpending99",
  },
];

export const DEMO_JOINS: Join[] = [
  { name: "Amaka#2201", ts: Date.now() - 120_000, room: "ng" },
  { name: "Kemi#0092", ts: Date.now() - 300_000, room: "global" },
  { name: "Chidi#4410", ts: Date.now() - 480_000, room: "tech" },
  { name: "Baba#12", ts: Date.now() - 700_000, room: "sport" },
  { name: "Ife#830", ts: Date.now() - 900_000, room: "ng" },
];

export const DEMO_NOTES: Note[] = [
  { id: "dn1", text: "New feed posted: “Lagos night market still hits different”", ts: Date.now() - 3600_000 },
  { id: "dn2", text: "Ad approved: Glo data bundle", ts: Date.now() - 3000_000 },
  { id: "dn3", text: "Ad approved: Spotify Naija mix", ts: Date.now() - 2000_000 },
  { id: "dn4", text: "New feed posted: “Best jollof is not even a debate”", ts: Date.now() - 7200_000 },
  { id: "dn5", text: "Amaka#2201 joined Nigeria", ts: Date.now() - 120_000 },
];

function track(partial: Omit<MusicTrack, "embed" | "platform" | "url"> & { url: string }): MusicTrack {
  const parsed = parseMusicUrl(partial.url);
  return {
    ...partial,
    url: parsed?.url ?? partial.url,
    platform: parsed?.platform ?? "Link",
    embed: parsed?.embed,
  };
}

export const DEMO_TRACKS: MusicTrack[] = [
  track({
    id: "demo-track-1",
    title: "Ye",
    artist: "Burna Boy",
    url: "https://open.spotify.com/track/0Lz23DJfAk0YbdBFjyj3vd",
    cover: poster("#14351f", "Ye"),
    genre: "Afrobeats",
    album: "Outside",
    author: "Kemi#0092",
    ts: Date.now() - 4000_000,
  }),
  track({
    id: "demo-track-2",
    title: "Essence",
    artist: "Wizkid",
    url: "https://open.spotify.com/track/5uU1uuyaUIBOiiUSQG7Wl3",
    cover: poster("#1a2744", "Essence"),
    genre: "Afrobeats",
    author: "Amaka#2201",
    ts: Date.now() - 8000_000,
  }),
  track({
    id: "demo-track-3",
    title: "Calm Down",
    artist: "Rema",
    url: "https://open.spotify.com/track/0WtM2NBVQNNJLh6XYJR5Te",
    cover: poster("#3b2a16", "Calm Down"),
    genre: "Afrobeats",
    author: "Chidi#4410",
    ts: Date.now() - 12000_000,
  }),
];

export const DIGITAL_TRACKS: MusicTrack[] = [
  track({
    id: "dig-1",
    title: "Love Nwantiti",
    artist: "CKay",
    url: "https://open.spotify.com/track/2eSW2VG9nzt1KtJIp9QqXH",
    cover: poster("#2a2438", "CKay"),
    genre: "Afrobeats",
    author: "Spotify",
    ts: Date.now() - 5000_000,
  }),
  track({
    id: "dig-2",
    title: "Last Last",
    artist: "Burna Boy",
    url: "https://open.spotify.com/track/1bDbXMyjaUIooNwFEFXJTC",
    cover: poster("#14351f", "Last Last"),
    genre: "Afrobeats",
    author: "Spotify",
    ts: Date.now() - 6000_000,
  }),
  track({
    id: "dig-3",
    title: "Peru",
    artist: "Fireboy DML",
    url: "https://open.spotify.com/track/7uoFMmxb0vgJfB9e0o5xjm",
    cover: poster("#1a2744", "Peru"),
    genre: "Afrobeats",
    author: "Spotify",
    ts: Date.now() - 7000_000,
  }),
  track({
    id: "dig-4",
    title: "Unavailable",
    artist: "Davido",
    url: "https://open.spotify.com/track/3nqQXoyQOWXiESQjSNW8eK",
    cover: poster("#3b2a16", "Unavailable"),
    genre: "Afrobeats",
    author: "Spotify",
    ts: Date.now() - 8000_000,
  }),
];

export const VIDEO_SECTIONS = [
  "Movies",
  "Nollywood",
  "Trailers",
  "Music videos",
  "Comedy",
  "Sports",
  "News",
  "Documentary",
  "Shorts",
  "Interviews",
  "Kids",
] as const;

export const VIDEO_CATALOG: Record<string, { id: string; title: string }[]> = {
  Movies: [
    { id: "xjDjIWPwcPU", title: "Black Panther — trailer" },
    { id: "_Z3QKkl1WyM", title: "Wakanda Forever — trailer" },
    { id: "3RDaPV_rJ1Y", title: "The Woman King — trailer" },
    { id: "sYc1gUwXJk0", title: "Coming 2 America — trailer" },
  ],
  Nollywood: [
    { id: "lQjFGCqE_6E", title: "The Black Book — trailer" },
    { id: "oqkz5k3f1nA", title: "King of Boys — trailer" },
  ],
  Trailers: [
    { id: "TcMBFSGVi1c", title: "Avengers Endgame — trailer" },
    { id: "8g18jFHCLXk", title: "Dune — trailer" },
  ],
  "Music videos": [
    { id: "iuoQyKbwzN0", title: "Burna Boy — Ye" },
    { id: "CQLsdm1ZYAw", title: "Rema — Calm Down" },
  ],
  Comedy: [{ id: "5qap5aO4i9A", title: "Live sample" }],
  Sports: [{ id: "Nq4NIpj9K0I", title: "Sports clip" }],
  News: [{ id: "9Auq9mYxFEE", title: "News clip" }],
  Documentary: [{ id: "5qap5aO4i9A", title: "Doc sample" }],
  Shorts: [{ id: "CQLsdm1ZYAw", title: "Short clip" }],
  Interviews: [{ id: "iuoQyKbwzN0", title: "Interview sample" }],
  Kids: [{ id: "sYc1gUwXJk0", title: "Family trailer" }],
};
