ALTER TABLE nf_ads ADD COLUMN IF NOT EXISTS coin TEXT;
ALTER TABLE nf_ads ADD COLUMN IF NOT EXISTS link TEXT;
ALTER TABLE nf_ads ADD COLUMN IF NOT EXISTS image TEXT;

CREATE TABLE IF NOT EXISTS nf_wallets (
  coin TEXT PRIMARY KEY,
  address TEXT NOT NULL,
  ts BIGINT NOT NULL
);
