ALTER TABLE nf_posts ADD COLUMN IF NOT EXISTS views INT DEFAULT 0;
ALTER TABLE nf_tracks ADD COLUMN IF NOT EXISTS views INT DEFAULT 0;
ALTER TABLE nf_ads ADD COLUMN IF NOT EXISTS views INT DEFAULT 0;
ALTER TABLE nf_ads ADD COLUMN IF NOT EXISTS kind TEXT;
ALTER TABLE nf_ads ADD COLUMN IF NOT EXISTS video TEXT;
ALTER TABLE nf_comments ADD COLUMN IF NOT EXISTS parent_ts BIGINT;
