ALTER TABLE nf_profiles ADD COLUMN IF NOT EXISTS kind TEXT;
ALTER TABLE nf_profiles ADD COLUMN IF NOT EXISTS stage TEXT;
ALTER TABLE nf_profiles ADD COLUMN IF NOT EXISTS genre TEXT;
ALTER TABLE nf_profiles ADD COLUMN IF NOT EXISTS website TEXT;
ALTER TABLE nf_profiles ADD COLUMN IF NOT EXISTS brand TEXT;
